import 'dart:convert';
import 'dart:math';
import 'package:espad/views/cards/chack.dart';
import 'package:espad/views/cards/get.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../views/cards/add.dart';

class CardsProvider with ChangeNotifier {
// ==================================== Navigator ==============================
  gotToCardPage(context) async {
    await Future.delayed(const Duration(seconds: 2));
    Navigator.pushReplacement(
        context, MaterialPageRoute(builder: (context) => const Cards()));
    createUserDefault();
  }

  void gotToAddCardPage(context) async {
    search('');
    await Navigator.push(context, MaterialPageRoute(builder: (context) {
      return const addCards();
    }));
  }

  void sendItemsToCheckPage(context, item) {
    search('');
    getItemCard(item);
    Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => const CheckCard(),
        ));
  }

//============================create users======================================
  final List _cardInfo = [];

  List get cardInfo => _cardInfo;
  final _chars =
      'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  final Random _rnd = Random();

  String getRandomString(int length) => String.fromCharCodes(Iterable.generate(
      length, (_) => _chars.codeUnitAt(_rnd.nextInt(_chars.length))));

  createUserDefault() async {
    final preferences = await SharedPreferences.getInstance();

    Map data = {
      "ID": getRandomString(10),
      "name": "John",
      "family_name": "Stewart",
      "address": "manchester",
      "birth_date": "1991-01-13",
      "mobile": "09052233568",
      "id_no": "4980011111",
      "image": base64.encode((await rootBundle.load('assets/images/image1.png'))
          .buffer
          .asUint8List()),
      "deleted": false,
      "is_active": false,
    };
    Map data1 = {
      "ID": getRandomString(10),
      "name": "Jack",
      "family_name": "Stewart",
      "address": "New York",
      "birth_date": "1991-01-13",
      "mobile": "09101687627",
      "id_no": "4980011112",
      "image": base64.encode((await rootBundle.load('assets/images/image2.png'))
          .buffer
          .asUint8List()),
      "deleted": false,
      "is_active": false,
    };
    Map data2 = {
      "ID": getRandomString(10),
      "name": "Natalia",
      "family_name": "Gomez",
      "address": "manchester",
      "birth_date": "1986-06-06",
      "mobile": "09211890565",
      "id_no": "8463830885",
      "image": base64.encode((await rootBundle.load('assets/images/image3.png'))
          .buffer
          .asUint8List()),
      "deleted": false,
      "is_active": true,
    };
    String encodeData = jsonEncode(data);
    String encodeData1 = jsonEncode(data1);
    String encodeData2 = jsonEncode(data2);
    _cardInfo.add(encodeData);
    _cardInfo.add(encodeData1);
    _cardInfo.add(encodeData2);
    preferences.setString('cardInfo', _cardInfo.toString());
    getData();
  }

//===========================get data SharedPreferences=========================
  List _duplicateItems = [];

  List get duplicateItems => _duplicateItems;
  List _items = [];

  List get items => _items;
  final List _deletedList = [];

  List get deletedList => _deletedList;
  bool showBtn = false;
  bool isChecked = false;

  getData() async {
    final pref = await SharedPreferences.getInstance();
    final getData = pref.getString('cardInfo');
    if (getData != null) {
      showBtn = true;
      var decode = jsonDecode(getData);
      _items = decode;
      _duplicateItems = decode;
    }
    notifyListeners();
  }

//===========================search from cards==================================
  TextEditingController editingController = TextEditingController();

  search(String value) {
    List results = [];
    if (value.isEmpty) {
      results = _duplicateItems;
    } else {
      results = _items
          .where((user) =>
              user["name"].toLowerCase().contains(value.toLowerCase()) ||
              user["family_name"].toLowerCase().contains(value.toLowerCase()) ||
              user["id_no"].toLowerCase().contains(value.toLowerCase()))
          .toList();
    }
    _items = results;
    notifyListeners();
  }

//===================================get item by id=============================
  var getItem;
  List itemEdit = [];
  String name = '';
  String familyName = '';
  String mobile = '';
  String iDNo = '';
  String address = '';
  String birthDate = '';
  final format = DateFormat("yyyy-MM-dd");
  String image = '';
  List dataUsers = [];
  List userIdList = [];

  getItemCard(item) async {
    itemEdit = _items;
    for (var i in _items) {
      if (i['ID'] == item) {
        getItem = i;
        name = getItem['name'];
        familyName = getItem['family_name'];
        mobile = getItem['mobile'];
        iDNo = getItem['id_no'];
        address = getItem['address'];
        birthDate = getItem['birth_date'];
        image = getItem['image'];
      }
    }
    notifyListeners();
  }

//====================================update card===============================
  editUser() async {
    var dataCard = [];
    for (var i in itemEdit) {
      if (i["ID"] == getItem["ID"]) {
        i = getItem;
        getItem['name'] = name;
        getItem['family_name'] = familyName;
        getItem['mobile'] = mobile;
        getItem['id_no'] = iDNo;
        getItem['address'] = address;
        getItem['birth_date'] = birthDate.substring(0, 10);
        getItem["image"] = image;
      }
      dataCard.add(i);
    }
    String encodeData = jsonEncode(dataCard);
    final prefs = await SharedPreferences.getInstance();
    prefs.setString('cardInfo', encodeData.toString());
    notifyListeners();
  }

//=======================================add card===============================
  String addName = '';
  String addFamilyName = '';
  String addMobile = '';
  String addIDNo = '';
  String addAddress = '';
  String addBirthDate = '';
  String addImage =
      '/9j/4AAQSkZJRgABAQEAYABgAAD/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAADFgAAAzMAAAKkWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPY3VydgAAAAAAAAAaAAAAywHJA2MFkghrC/YQPxVRGzQh8SmQMhg7kkYFUXdd7WtwegWJsZp8rGm/fdPD6TD////bAEMABQMEBAQDBQQEBAUFBQYHDAgHBwcHDwsLCQwRDxISEQ8RERMWHBcTFBoVEREYIRgaHR0fHx8TFyIkIh4kHB4fHv/bAEMBBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/CABEIBQoFCgMBIgACEQEDEQH/xAAaAAEAAgMBAAAAAAAAAAAAAAAABAUCAwYB/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAIDAQT/2gAMAwEAAhADEAAAAe9HpyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGzjW35cRkrHqOOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2TxFWkiKo999nPaXdaOIW7e5WORwMD2mwi6QGsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+bKr3XUjO6mVMSxyOUAAAABjSS6nSQ1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS5RNltNi6qdIR0OdAAAAAAAA57RLib5BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9sZV0612Z3HkEUAAAAAAAAAABGoeniVNEzw2gOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL4iT7GRlencRQAAAAAAAAAAAAAEel6LCp5pNhbQHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZKt86hzzOg50AAAAAAAAAAAAAAABW2Q5df0m+esVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb+NVvI342E0AAAAAAAAAAAAAAAAAAA17BQRenqNIgDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPlhc+5Y6BzoAAAAAAAAAAAAAAAAAAAAAcVdX1FfpNONoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEvjZcPcNA50AAAAAAAAAAAAAAAAAAAAAAACvp+oq7mrGsB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADmzoY8vDQJoAAAAAAAAAAAAAAAAAAAAAAAAB56KKJ0fPbRiLkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNhdDHd4x0AAAAAAAAAAAAAAAAAAAAAAAAAAAVlnj3nMtmv0ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLyFNw0CegAAAAAAAAAAAAAAAAAAAAAAAAAAAVdX0fOawGkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMsZkrrIw1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAUF/V1NWN4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW1TfZ9lDLQAAAAAAAAAAAAAAAAAAAAAAAAAAAABFlYHND05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOk53psbCKAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjm9cuJ6MgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABv6Ggv8ACwmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKaBZ1m+YVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZeUt1jYRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZVW1TtmF8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAn3NNc4WE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAABX09vUbZhfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ9zS3WNhFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV9Pb1G2YXwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZeUV5jfoigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK2ptKvbML4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJv8AnuhwsJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqrLCv2zC+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbOk5rpcaCLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApYMyHtkFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHUcv0mNbBFgAAAAAAAAAAAAAAAAAAAAAAAAAAAABxQRt+j0ZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0XO3+VSRnYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHN68sfRkHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9orrOpwysAAAAAAAAAAAAAAAAAAAAAAAAAAAAB57rObHoyDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcU9rHbMY6AAAAAAAAAAAAAAAAAAAAAAAAAAAAANO6MUA9OQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzrLCO3Ax0AAAAAAAAAAAAAAAAAAAAAAAAAAAAARJcHvKUejMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB75fR2vlz2VhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAACNJFNE6TXc822a9YDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADf0NDfYWE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT19pV7ZhfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN/Q8z02NBFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU9fLib5BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0XO3eVTRnYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwOe1noyDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaVc2e3bz3DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEl13eVA9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfo9nvTjDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT3FFUxBvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSbIkvz6hwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5zoeZuQ2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2sqa5w0CegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR+fuabXML4HQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG3o+X6DG5AigAAAAAAAAAAAAAAAAAAAAAAAAAAAABiVEDZr3yCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRHcXc3l+jxvaJoAAAAAAAAAAAAAAAAAAAAAAAAAAACLX6NGkBrIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7pLPPtqMtAAAAAAAAAAAAAAAAAAAAAAAAAAAGGcMox6cgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmN7Pem9wzw0AAAAAAAAAAAAAAAAAAAAAAAAAAAVVrQ1MUbwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABey6q18+gc6AAAAAAAAAAAAAAAAAAAAAAAAABjzV5RaQGsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASb/l+kxvYIoAAAAAAAAAAAAAAAAAAAAAAAAACqrJEffIKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALmmmR28GOgAAAAAAAAAAAAAAAAAAAAAAAADVtru8qB6MwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHvg6TZXWPn0DnQAAAAAAAAAAAAAAAAAAAAAAAHP3PPXIbcBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/oeXvMbmCKAAAAAAAAAAAAAAAAAAAAAAAGsrK7LHfIKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN+hx0/tbZYaBzoAAAAAAAAAAAAAAAAAAAAAConUFyG0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe3/P7470LHLHQAAAAAAAAAAAAAAAAAAAABjlTd5G0m+YdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxeTK2yw0DnQAAAAAAAAAAAAAAAAAAAMeZ6Dn7gNpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtLSrtPPoHOgAAAAAAAAAAAAAAAAAAARaG+odIDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALexgzvPoHOgAAAAAAAAAAAAAAAAAAAaOe6Tm9IDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL6Vp3efUOAAAAAAAAAAAAAAAAAAAAPOY6jm7nWNoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGzjo/Tz6gAAAAAAAAAAAAAAAAAAAAOf6CkuYQ2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIjzYXXpjqAAAAAAAAAAAAAAAAAAAAAqbau7yoHozAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWdZcR2wGOgAAAAAAAAAAAAAAAAAAAACJL095zo9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9qrvGtoiwAAAAAAAAAAAAAAAAAAAAHno5dNib54iuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW09n59Q4AAAAAAAAAAAAAAAAAAAAAAAY5CJSdNQXMYbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA26pkrv0w1AAAAAAAAAAAAAAAAAAAAAAAAAU1zWVyqG+YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzrLvPs0ZaAAAAAAAAAAAAAAAAAAAAAAAAAIkvA5oenIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0lH0GNhFAAAAAAAAAAAAAAAAAAAAAAAAAPPRz2ixrt8goAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrS00b/PQc6AAAAAAAAAAAAAAAAAAAAAAAAABEoun5zSdY14CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEtbZ93jLQAAAAAAAAAAAAAAAAAAAAAAAAAABVWuHec0nwds/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCdZR2rs5KL89J6AAAAAAAAAAAAAAAAAAAAAAAAAAAAA1bRUV/T6rnnFnXaRiKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLjH2ysY7V2O9nYc6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwzFXX9JjU8yt67WNIoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJXEXbbTM7r5+SOhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0Qq2/Vzl1/XXMEXIdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGywlWTrXZncaSRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGmBau85vX00K5pkiPpIdAAAAAAAAAAAAAAAAAAAAAAAAAAAADPjBY2EdqbCaivPSaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARpIpoPT67nm1rA0jSKAAAAAAAAAAAAAAAAAAAAAAAAGU+VdJt5GdwJuSehzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0RK+7d5y7o4FzVturSQ6AAAAAAAAAAAAAAAAAAGXGKwsI7UWE9FY5E0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5EmOqSH0+qp5xaQNI1CgAAAAAAAAAAAAAB7OlAkW8mLr52SOhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0Q6+8Vzl3RQLmsbNdyHQAAAAAAAABtspVk+yzyvXsJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADGFPd5z8fp4dTSJMbWQ6AAAAAMrKVfaTssrxyJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEluqCN1EG4pWzXpIdAD3jyXMsc607jOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMau2d5y6+pdo1iubLzLdhoE9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa9goIvTw9ZnDKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//EACoQAAEDAwMDBAIDAQAAAAAAAAIBAwQAUGAREjMhMnATIjFAIzAQIKAU/9oACAEBAAEFAv8AGXsOvRcr0Ha9B2vQd08Lo04tJGcpIqUkdukbbSk/ovSn393hNEVaFhxaGLSMNpQoifpJURHnlPwiLbhUMVaFhtKRNP2LUh3evg4GnCoIqUDYD9CY5ongwAI6CLQNAH05C6veCm2DKm47Y/Wljo74HRFWm4xLTbYB9h5tHAJNF8CIiqrcZaABH7b7SOIQqJeAU601GVaABD7zraOI62Ta5+0wZ022IWEkRUfYUc9AFNWWBGyvx0Kl6LnLLClQigpZnmhcpwCAs2FFJWWEC1GKGLzKt5q02ritNi2lrXrT7GmZsMqdCiClukMa5jHY1uUhndl8ZnddJLO7LY7W9brKaytoFMxRBG7SW9hZTGb2Bd3B3iSbSyeI3uO8zA6ZOyOxu8qmqODsPJYY7nL3NDpksQdrd7dTcGSAm4kvskdruRxE1dvs5OmRwU9l9kJqzkcZNGb6SapkYdBvz3R3IQ6nf5fNkLHV6/zeTIYvPf5+RQ+a/wA74yGFy3+b2ZDB5b/N48hg8t/ncWQweW/zePIYXLf53HkMPmv87tyGJz3+dkUbnv8APyKPzX+d35Czy3+by5CHff5nN4hlc+RB235/myJnivzvLkUfhvxd2RRODxDD4r6fZkcHjvr3FkcH4vsnhyOBfpXBkcHvvszhyFEVaGMa0wz6ZX19v1BWKVGBBkEdtAHATFCFwdh47HTV7A5ye7HYvPgc/Ho/R7A5y+7HQ6Fgczq9jzS6t4E6urmPQ11ZwE10HH4OBSeDH4a/lwGcvsx+Ouj2Azl92PiuhYDLX8+QN9mAPdXcgi8N/X4X5yCCvtv8hdGshhL77/NX8WQsltdv81ffkTB7276q6I4W48iYcVsvXbvhvACvv7kyUF3Den11dyaGurN5NdByeCt6lLozk8VdHrzNXKBXQkvMpdXsojLqzd1+CXUsogleJK6M5TGXR27zlypOiguo3aQW53KoZatXVwtoZXDLR26zS9uVouiguo3SSW53LIRahc3i2N5bHLY5c5pe7Lox727iZbRJVIsujnsO4zD65hEc1S3vuemHzmI6orDiOBbSXRHj9Q8yYP0zS2zHNSzSIurVrLoi6quaQe21vr+HNYFslcGawfi1yeDNYPZa3+HNYfFa3OzNY3DbF+c0Z47Y7y5oltk8+Zt8ltmcuZxue2zvnM4fLbZqezM4FulcOZwuy2vdWszi8NtXMutCy4VNptC3OsHuVFTL2WA2CiJclomGyok0LLB+LpJTR7K2ert1m8mVw01eus5PblcFLtKTVnK4afhupJqOVgmg3aQmj2Ux01du81OuUwhvEkdzWUsjtbvDo7HMnihudvMwOmTNsGVNNo2N5JEVHIypS6pkbccyptoAvxgJ05GWlRUx5NabjktNtgGBEIlTkaiRRxpEVVbjKtNtiGDEKEhxqMCHFgEipuNQAIphKpqjkYVo2zDEgbM6bjIlIiJh7kcCpxgww5tgypuOA4o40B0cYkpU0whEVabjEtNtAGMGAnTkajEhwQGzOm4qUIiKY2qa05GBacZcHAG2HCpuOA5EbIHRxiSlRUvQiRU3GWgbAMmIRKjjJRtmF2Blw6bjAlIiImVGwB0cc0pdUuAipUEVaBsAzAgEqOKlG2YWwGXCoIwJSIiJmhsAVHHNKX5soipUEam2wDOiESo4tG2YWJtlwqCMCUiImfmwBU5HNK6p9xEVabjEtNtAHgQwE6ci0YEP2AAjpuLQCIp4HXqjkYVpxkw+o22Z03GFKTp4NcYAqcZcD6DYEdNxhSk8IuMgdOsmH7BRVVqNSIieFXWBKjbIP0tMEdNgIJ4XVEVHY39kRVViOg+HHmRcpwCBf4bBTJlsW08OmKGL7Kt/w2CAPh9eqf8AM3/pV//EACMRAAEEAgIDAQEBAQAAAAAAAAEAAjFQEUBRYBIhQSAwgBD/2gAIAQMBAT8B/wARYKwelAH4vEoN5WB+Cc9HAJQbysD9uPzooyUG8rH8jPQwCUG4lYx/QhHoAyUG86BblEYm+AygMaZbi7HtAY1i3FyPaAwNgj7bj36QGBtEfbWSmjA3HD7aNG6R6RsxG86yE75iybPUW0BmxEUBmxEUDpsRFA6bERQOmxEUDpsRFAZsW0BmxbQGbFtAbFs9RbPURO+YsQMoNxQeKIxXiKIzXtojNe2eoiaExYChMWIoDFi2KB02LaAzYj0gcneLs2bZ6iN0xaFCNx1q3cM2rTtk+kbXKEbTj8t2n5tE5NuJQOdhx+XLTjXJwjclCNZ12I1nXRQjWd1Ex1ExdCdcxdNnXMXTdg9SMWwnbMWzZ6i3cM2oGBuOH20a33ndPsLGLENygAKAtCIImslBqAxSFuV4kTUDJQbygMVBGUQaQAlBvKxisIBRbwsY3sINQAsSvFeO0ASg3lAYtiAUW8auEGoAXcrxXjoDJQbygMdAIBRbiP6AEoDnopAKLeFjH7Ayg0DpMot+/iSg3700jKLcf8DcdQ8f9Lf/xAAmEQACAQQCAgEFAQEAAAAAAAABAjEAEUBQIUEyYAMQEiAwUYBx/9oACAECAQE/Af8AENx3X3CvuB9KLATRcUXPVfcaJJn6qvZ9HZgKL/yixM/mi359FJAmi/8AKLEz+pY9DLATRcmKJ/YrW4rjr0AkCaZyeBV/3qxFAgi43zPaixPJwgxB4pWBmd2SAOaZieBjK3R3LGwpmuchW627Gwom5vlK1uKG1Zrm2YrX42jNYWzQbHaMbnOQ3FtkxsM9TY7Jzxng87J880sbF50CeOxedAnjsWnQJ47F50CeOxedAnjsXnQL47F50CxsfkzzSxsfk0AjYvGeJoRsXjPE7Joz1nYs1uaLE597UrkTQt1r3nRL46950Sxr/kjRCNe/joVnYNGhWdgKM6BJ2F+qYWOgQcXq+wcd6BRYbEi45plA5Gcqidm44zQOdowuM1RztWFjbMQd7VxzfMUWG1YXGWBc7aRRFjbKQc327jvKUWFtuRcURY2yEW5vuWW4x1W5oCw3N+qYWOMm7acb443bTjfHuhRnGSd0Yx0ndNGOvlum8ccTunbi2QpuNv1RNzlIebbZoy1nbOeMsHnbOesxTcbVjc3zEPW0ZgBYZoNjegQY2BouBRYnQK5E0rAxrDxNFwIosTOkVyJpWB1BIE0X/lFiTc6hWIpWBmv+aMsBNFyYonWBiIoP/aBBjOPE0XAiixOxvaKDnugwOUWAmj8nQokmdsGIoODNA3jEPE0XAiixO7BIig57pWBwCwE0fk6FEkz6AGIpXBmr3j9bMBTOT6KCRFK/RoEGPzZgJosT6SCRFK/Rq94+sTTN0Kvf0wMQeKVgZn6MxPqCt/pb/8QALRAAAQMDAwMEAgEFAQAAAAAAAQARYAIhUCJwcRIxYTJAUYFBkTADECCgoVL/2gAIAQEABj8C/wBMu1FX6XoK9C9P/V6dmPQV+Ar1ldivQFb/AAdNTanZNgHXZler/i7OrBv4XNkwtTsjakrVV+l2dMB/Kw9I2P8AStVStSPYdA2N0glayrD2dWxfbpV9XtudiGF1rLKw9wyY7CsAStZZNSPd/BTG2wb12TUj3zFXvsBewVhgWN09NxPWpDpzc4V6LFMQ06eqwTC2H8piJuwTm5xTFfImtrJhjGT0dviZubUphbH9VH6mPVXkuqm1S7NLuurtlOqn1S1z6ct10/crYJhl3HpMqv3zHSmMo6vwM11iTsgM1dGmTP8A+c4Kx9ybnOEJpIB5zx8yR/jPU1SSo56qSU55pIB4z9UiAgBkVMAHEipgFO0VMi+oAOZEeIAOZEeIAOZEeIAOZF9QAc7RUyIQCmRUwCmRUwCniRU8wD6kQPneKqRjP1SOnjP1cyOnaIbwVSQ856viSVZ6qSVZ6qSVbQMFeyfqfPM7KxBWoNIPMCYo0x6mCUmPUwSiPUwSkR4HaOkwOqP8QImQVCBVSBoEB5kFMCpEgB2jBgNRkI2iIgFRkREAb5kVJgAHxIwc+apH4XfONUWXTR2kwPzm6uZPwc0TKKqf1mjKBmqaZQ6fMnxKRmXlNVOYMqGYFMqdA5cytvjLEyxvnLCmWOgcqZb0/GUJlwOUFHxL+Mkainl/jJdAmPQfrIP+fxMnCf8AeOcp9oegTUeLYx081q5xlXE2qxlU2qxlU2POMq4m33jKuJtTtFTxjaudoqppTzjvqaU46maP4xwPmaVY4zQnzjquJoNoOzrsyAx5IurgiXgm5KsMn2ZEeZa2VqllIywPjaKk+ZZUcsZZzliJYB9ZeqVU5gVSo1ZgyoDMkSh/wM11j7k7nSmGaYrRdXBEjvpVhntQdaC6YgiP6rKwgVw60FMQY1YOtZZaRBrh09BTVBotpDrWtIaFXT02VxErBai6taH/AAV2eHOzcq+qKXC06kzNCLAlaiysIxqDrQVqBEE0hay6sGjl1p0rs8A+FfVIrhabpiGzTUgrWWVhJrhaSrjLdmWrUrSvsytdXcZCwdayysJhqDrQVcYzsy1alaa9mVrr8jDMA61FlYTrUAVoqZXpwXZuVq1K0/7Mrak3vGAJWqysNhNQdaCrhvcaQStZWkNsRdabK4f2mkLVdW2N7MV2cew0hPVfZJ+xXyP5GCevZa1itQ/hc2C0jZi4T/0/1/kwCeu52c+CmP8AdgF52eYpxen+zDaC6/P+yr//xAAuEAEAAQIEBQQCAgMBAQEAAAABEQAhMUFRYFBhcYGRobHB8HDREEAw4fEgoID/2gAIAQEAAT8h/wDjKBW0vShMRzJULh3rV9yfuvtH7p5Dnc+GmRRMLY/hYFYBXQJrD4OYB607FLqr+qzw6EetHxR5rWGd8KAEAOhH/hgUgF1pr9zHN/CbEhaAvtUOoGqk0Ov0Fa9c1aHgByP8LJAF1aZwBsZvNo/B/T2q+xnNYKywagrPyjFZohADp/kgEtgxpbwJYzXV/B33Cr6IHNsUCFnULFR8RM0l80f50lMcemn4M6U9nl2IPNM3h5BPrRRCOrj5o/otIh1g7W/BRdguuBrUMsDm4+KuAlq0AEAHb+J/pNI7FhJ1z/BDICnAiaiGBoYtCWx1cf6/WmCslx0aRwSGE/ApJQ5GNOh6QuvVoGAFRR/ZlWCWfimQqNc+Z+AgoAVWwZ1cBGmb+qIgGvP+9FXomJUAEHBMHf5UQjnOL0o/OiFzeAogA4jUrLm6m/McKmg1OXeoXq7gdOCNSF4xMn/dFkCLI76hJVvGbRIQHBwb2GCY1YS0TBN7xlVyqE+FKOExzkaYUlcHTk145b0x4BiuVQB6ubwwAUCJcpmzOfMdOVTbePXCsYfUaAAAwOHnIYcXI8+tXGEhLI4m75zyzpmFBiDjREQWMuINHhfcpEUZCyOJu3vFTIUGA58UgpADDWmZhIi0OJuvG1NgwfPKi1gjittK+TXnuslazXQowUAWKz4o04a1qwScnTdONi62jWrli3f4OLCqzp0KEYee6LgNHm0cZljXLPTWvbcxKgxWDrQ6SX651nxhokLhL06GTZ5Zfee5WhsrXTq8bcKkClLU0PG5YVS93bLjnNcpEZFxR657kUXFhRAgMOONWmWUnfH1ncfSr6wHrx7ohTzf43H161CnFQ8f949bmIT4r5vuONak8ekdQlJd5P323GOXA9OPNGHzU3EeZIebbAF7UHcRg85/jPjxvfV3cRnkS+jRWfHhd8n43Fgch2Bi+buLH6vc2AfTem4vVfc2B9/k7ha9R9zYH0uTuL1X3Ngff5O4sfq9zYH2uTuLA5jRx/Bar7bi9A+1GPH7Tv8AjcXv/Z/jPjuVK55PxuL1/wDGfHsBze+4rH5PejDj7kmg93cSjRCjDj+JyA3Ea6UYcf8AEj2Nx3PyPbjzV6843HieX2OPOFY3V++4uWtOX5cfdzqr6u415X3ePNijAddxfqr+laz47amg+1fvcXOlb0+Bx5x1vtuTD6J7ce9N802tpuNYeQ+/Hre17lOPTceA5Dx5wuaVr13CyArlBNFCg6N2lV3CMI0/XHoE4kzHJop2SImkIROFrbfJUCZbEVdcTuuwmQiNOhNm3M28BXWfF/iis9g5UQTFE8f929772f4z2DlXyfG3lL5x5t80YbDk0Avn/m3ly5Hw0YbCcKUhoB8/O3+dAbDm2qxt7lUAak+dhcixacZ291wzpW5w7Ccajb1rN9dvdaiSwRPbYUBsWXo0ept+R6sebfNGwZNML5/5uDkQj4Zo2DMjQD5+dwc9L055Y2C+rJuFzy5PXYFqeVOU6s7gSptMz5/5sDoZHm1R9+9NwdKhyiT32BDBmB6V+2NwzJgMPe2wJy5L99xXyq4ksX68eBFYDGmazbHLL7y3GqYl4hj1KLYNViIZOv8AGfGWmrFE3GKmppYrN+nLcv0rlOHjTU36Dtbc8Aah8/PGuRAtOK6/fnc99OT0fXjVu52K+Hc/LiI/e3GWowNVfvfdCEMkTszSEBmTxhqMGAA7f7d0fNqnulv1xhglwKRliqvf67pxDWT5+OMWy3SCuhzOn03Tf+DZ+9Qo4vdPq+x87qSAxETtQkYIPFnCpmYDB23V0q8sVB0y4q1ypKlbriq9c913I2Md+LRkYmV6G7GEYjJ2oTcEHijU+GxY7Y7s64Z1KLFSdHigq2Yg61K3cc92ypg2ej9KOJNSgwuerhu+0Lez9cSC2AJacJus7u7TUOuKzyKEbmHEZQ2F150bv6kmZV87mLUrnw8swrDVpVKsqyurvFCREZEqALJYaPDgdIDGlkyBYOW81FmRsnKkIJceGNIDQF150b0u7H2MPSOGIdYBNNCbqr3+u9Vb6vPDIqWEGhHjehXw/PDPa+5WvXep8p7cME9HeuPhrF6/DhhkOap++N6mOpfHDBJaqow3qY73u8McIqxGjvUQfL7cNMDovd3pyqwjlw0x1B9DehkNQetHDGsJ1HzvQyHNfBw7Eck8b0N+hPtw77Zk0XN5YeaF3yD34ce3D61+t5OD0odd8Dhwh6quX3DeYjnr7vDhaNaSLaW3iCYEtAmr9MarEdqVfEAeHwYBMkNyn4Q5kbu9omoroBZwvQsAHIjiQEhBOZVySnS1Z0Qhem7DGNbeasGgjijaolqz5N2HmyPhn44sYFgw8L+92QDoL8fPFpNIjz/zdfSr+XYOnFrfyuV0w3XAHUvx8cW50FOKaffjdQTYxWKIjIPDizhUNyWTvfdUOcBl7Xo4s1GbMh7f93Tk1jedj59jjFhZX+9q1jt03RGWtq1Pi/XOsuLtyGrB4NumXpuiCRmrq5UcYamBXLfBqNynftUeEOeLV6LN1407CRIavTIYDjRREDEctxAzAKuAEzV8tc7rV1CTNxox444URAfCjSwNMHzTrCMk28EgCrgBNX9RxjNoa11cfP8AE7ANguynxmNF+aehHmbaJDLQqOYGhjQUQauexooQ0aPFHJfmm5GhiztXHTvSoItTKs99j91AgGyggAlTaz0yrHxNcvNHa+0XLyaxAd6uTLG1ijYANnJrU2h0i3irkQGYT6bNKg1A52L2q9iWqUAEAHbad+AdSzV7QPFIlJGSQnbZDIIaBNICR0CX/VYMLq3dsAQGi1ys/tP7pWOaRZ2Ixfb3Ug81iHWMFio0Q6VFG2gEARq4pWhh4qVWAzL+nHy7ASuBUIpFzbPirkJap8UAWA8bhwpHUxq9OPhP3TKhHKHjTogmeVKhDkL+tGWx1zo3I0RBJ0pV2HRwq/LGph54r57VGJBq29KgVK52PFRAAcjdTcvV6ualX9x5WaCIE0SHxxBsGXKmXxGBj5qOi6uNG7nCiYDRJSLocmsawM5k80cKMc+1RqQatvSolSudjxUSIHI3o6Na2OZan5YfD4opBE0SHxwXHTvTwpGlO3iTgX9awanVxo3x1o2AMpKJulmD+6vyAZzJ5o7X4B9wq4yGtlRClaNjxRMEDkb+cKn265lqusR0h8UiKETJLn9xkQaBNQCw6BL/AKq7Aurdo/AeHPurM7T+6RhskxZ/r/cKYi4XcAosZnGC3moUA/BBIAI4zVzc9MvFSSgMzDxX3D+l0pCJDNbBUSuemVEEAAwAt+DGrmc0VfIDmfqvuH+bp7UrCJmpYqJWfpQCwEH4QavokzKxA54V7ZW/xigXtNAXRcYMPNEQAGR+FGj1JyizWVhk5Pf/AAdaIJfXagAGur+GIkCZzTEpPN8UyKJCNxxP/JJCuAZ1gFihkUfhsGXkJUbY0TB/ktC1dDnUICUXdfw8sMRpC4jZ05NW0osfVzfxABACOJXOpn/+Q5/+RH//2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBxSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACT5nLPOEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSnHPPPPPIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSkHPPPPPPPKKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACctPPPPPPPPPPLOgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACevPPPPPPPPPPPPPPLCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJ5PPPPPPPPPPPPPPPPPGJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATnPPPPPPPPPPPPPPPPPPPPNyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXPPPPPPPPPPPPPPPPPPPPPPPJiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcPPPPPPPPPPPPPPPPPPPPPPPPPLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbFPPPPPPPPPPPPPPPPPPPPPPPPPDIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1PPPPPPPPPPPPPPPPPPPPPPPPPPPAIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPPPPPPPPPPPPPPPPPPPPPPPPPPPPLHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9PPPPPPPPPPPPPPPPPPPPPPPPPPPPPOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIfPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLJgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbHPPPPPPPPPPPPPPPPPPPPPPPPPPPKMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/PPPPPPPPPPPPPPPPPPPPPPPPPPPLKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFfPPPPPPPPPPPPPPPPPPPPPPPPPPPEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfPPPPPPPPPPPPPPPPPPPPPPPPPPPOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALvPPPPPPPPPPPPPPPPPPPPPPPPPOAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPEIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEfPPPPPPPPPPPPPPPPPPPPPPPPPEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvPPPPPPPPPPPPPPPPPPPPPPPLAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUPPPPPPPPPPPPPPPPPPPPPPPLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM/PPPPPPPPPPPPPPPPPPPPPJAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVPPPPPPPPPPPPPPPPPPPPPEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHPPPPPPPPPPPPPPPPPPPPPCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVPPPPPPPPPPPPPPPPPPPPPAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAPPPPPPPPPPPPPPPPPPPPPPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPPPPPPPPPPPPPPPPPPPPPNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9PPPPPPPPPPPPPPPPPPPPPCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL/ADzzzzzzzzzzzzzzzzzzzzyykAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCzzzzzzzzzzzzzzzzzzzzzzzzzwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHzzzzzzzzzzzzzzzzzzzzzzzzzywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfzzzzzzzzzzzzzzzzzzzzzzzzzyggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALzzzzzzzzzzzzzzzzzzzzzzzzzzgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDzzzzzzzzzzzzzzzzzzzzzzzzzzwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtzzzzzzzzzzzzzzzzzzzzzzzzzzzxg0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQfDzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwjYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyy4kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlIjzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzAsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2rTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyAskAAAAAAAAAAAAAAAAAAAAAAAAAAAAAksRzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxRYEgAAAAAAAAAAAAAAAAAAAAAAAAVqTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwC8gAAAAAAAAAAAAAAAAAAAF+RzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxRY0AAAAAAAAAAAAAAAnqTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzCsAAAAAAAAAAA17zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzww8kAAAAAAXbzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxQMgAAVvzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwiUCTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyBzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzjzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/8QAFBEBAAAAAAAAAAAAAAAAAAAAwP/aAAgBAwEBPxBNCAAAAAAAAAAAAAAAAAAAAgREREAQAAEABIAABAAAAAAAABQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/xAAWEQADAAAAAAAAAAAAAAAAAAAhgMD/2gAIAQIBAT8QoCwoCTAiIEAQICCACAACAAAAQQAQAhCIAEAiCI7u6qiQRAAIFTAGICEgACUBQSIgAEQAAhAABoiOogAQcEgEAAAQEACAIICAIgBABACECEBAAgAhAIQEACACAQAEAgEAAACy3//EAC4QAAECBAQFAwUAAwAAAAAAAAEAESFBUGAxUWFwEHGBkfBAodEwgLHh8SCgwf/aAAgBAQABPxD/AEzQAJE4HU2tWFJ+otmgQCgAaAF4APhGGJe6UpcnE/wEWkAkjRWC4bKHRAcUhgpPf4o0Yox9HIrmGydQJArECeGEsE0eEIPqE6MQWyMAAADDAhI/rPQqwgCURGex4LgAiwwGNb0YSCNisBwABQyeKdyTCBkPSia1nYgwK4HARaO4sBdfTy4BBMJ/NhoNIFA0erwHaJJivEy2Ed4AtCAxmOWKDFzkieb1uCxbtgkFSwFPGo6NCHuQ0Jlfoal4IwZ1FEgGikovvvGDJEk1yGz7WR2JBx5wBQp43hjShJ+OlIqZvYBZZ1KymDZIBJ3p5BQOj4TALlTgoLLFoGu8AAQIcxYsQBAAgyogpYErvrQgDAiWCHwKnjBASxdgADTSSgZAKrhOxXZj0RBVNVgB/B9ow0AAGKH6GCGh2jdxA5k3SK3OATEEwblaBgFAGdzp0ARVygPeIAJXMMyj1wdnKHO5lBAFkCoQWG0LxoGeCKfFd50G4xhXwE0aUi+64z+oRz9ivD/bQmLjgP8AWztGMwjpOvM3GuUpV0eDea2ggABuQyF9ZL4rxQ9JXED7xcQDHtm0Qse07RDj2y4gm2i4UNtJV8cF1hXEPqisAEx1O4htXjDcgSJlZV0eB3FAVfLErlCQQidcPAnuKQmsACe4xC1YiTrwrj6J80snXDwCe40x4YxU64eDlxJDFOaFeY3CorjAfRVeHqi2iAEeS3/LiwRV6sTF8wXIESvSFzDbkAVeE5SVxBK/wcIIMEpCWFGvBIK5x4OuosXACMACAABmEGwlmzCltCXgBWA7RBJgAO0bnIErhAQR0J2AbhHNOaK52EcLfRRnQPjL8rCB+s0XAB0yLC06MuEFBjDtYB+6V0QFEBKAeh1xghq9YEbhQmNg9AtII3CeHLBbwHxL9lxi9gr7FcdgCRD4r+vZuMMoyVOuFNBg5ZC5UrBiXA+EiJDGsjwACmIUgmUuX4flP7qo2hCi/qDW3kDwnueDFapGdjVM10A0k+lZZwroJiDLQjMBh12iDEgZuC/p8GrGC0OdogboEAzYHdX6faEBzgN2pQUEAsydUN2jhRHpIJ1U47Sud2EANEiIKrE8H9h4B5QSYGPA56qYDDMdQ+xEAGEFAxrg3LaNTEB5B9owYgPUCsPLaCgC3kxRHedEeSMSxgAqdIjPZuSLOkTvMG6NCosHBzprqAmr1ObT8M1MYogLaJLZGYMzk7/YwAMgNUzHkE72AU0poivRinU5qmNCF7KC9XT1MAOgNoYPEcL1aQzoDeWmDtGwTrAWzmvUwAH5phgEHP3ojqCPimFPZRiCvMOXUk6a+bNegA3nFE6b5ymvQ5/NOHDvQIWgDIUaCNOYKd/Z/gS8CMYEP9q+wtCPVJaKAcWtEP8AndqbQDoAafeyqEy7hAMIA0qhu58QCaDddEQE2cDbrj+Vc/TUeCBrrgAP4vYU6oUDxXaa4cKE9oGggbrAYb8Rh+cxukIkASM7yZ1gCCUJ3aLAjgIxHZLoAQuYkw4nWxMw7CFxmaxMQgABhXwOBbWq8DmWk05uhQJ3LfJYAAiHWixVucjCvDxY/NcCCt2mP6GsQkowlISJdbG0HiI+2CQVgA9wMDWv/lORuBZRsaMQQ/BAg7yzjaQAOWXoA8SCIAOXAFnOBmEaoI5U+EANjCzihsPGCpJhAyFpgKZjliRi7WU0gANcpiwGoIgM2vhWqWLGCcfgQAkiCAMqGcgcW4D/ABpAhd1QLDgNYABQyFSkBAZC4TwSHTSCnKJQSK5GuBhoMJnOGEe7iFxua+kHnmV9yIQbPesAg+ATBgUSYuoEH4uj/ZQ0eYapLUINeGNj1aBsWGt3XgPYZAn7qX90Q0wU4AKPjEwZFUmL0iQ4HxFBclJ0gO4QDjQzpjJLmt3XylwFYDnzE0IZMNCAGQOE5yQGTdJi/gBYcNUxnlZl2FfrgWRIKYR3FRUBJmZ+wgANlhk9SHGYDHgKwABlQnI3A2ILsKRHzuNwhMs19KDagyWHCFgAbGBBPrzls/ROvoRMGsIcjDQCAEAAS2ROncLUV+omBO6ZBDeokBY6wNlRczmgMNkDH6Ia2a/EmfGZu5swWnHACgKMVA/yQIBrEDL9oUAiinckzEPSYBsUAAgYuoa7QQcgEwKJCTi7Qim/1s3/2Q==';
  String addImageNew = '';
  final _chars1 =
      'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  final Random _rnd1 = Random();

  String getRandomString1(int length) => String.fromCharCodes(Iterable.generate(
      length, (_) => _chars1.codeUnitAt(_rnd1.nextInt(_chars1.length))));

  createCard() async {
    Map dataAA = {
      "ID": getRandomString1(10),
      "name": addName,
      "family_name": addFamilyName,
      "address": addAddress,
      "birth_date": addBirthDate.substring(0, 10),
      "mobile": addMobile,
      "id_no": addIDNo,
      "image": addImage,
      "deleted": false,
      "is_active": false,
    };
    _items.add(dataAA);
    final prefs = await SharedPreferences.getInstance();
    prefs.setString('cardInfo', _items.toString());
    notifyListeners();
  }

  //=====================choose image from update card===========================
  choose() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(
      source: ImageSource.gallery,
      maxHeight: 180,
      maxWidth: 130,
    );
    if (pickedFile != null) {
      final imageBytes = await pickedFile.readAsBytes();
      var base64en = base64.encode(imageBytes);
      image = base64en;
    }
    notifyListeners();
  }

//=====================choose image from add card===============================
  chooseAdd() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(
      source: ImageSource.gallery,
      maxHeight: 180,
      maxWidth: 130,
    );
    if (pickedFile != null) {
      final imageBytes = await pickedFile.readAsBytes();
      var base64en = base64.encode(imageBytes);
      addImage = base64en;
    }
    notifyListeners();
  }

//===============================check card=====================================
  reject(int num) {
    switch (num) {
      case 0:
        {
          name = " ";
        }
        break;
      case 1:
        {
          familyName = " ";
        }
        break;
      case 2:
        {
          mobile = " ";
        }
        break;
      case 3:
        {
          birthDate = " ";
        }
        break;
      case 4:
        {
          iDNo = " ";
        }
        break;
      case 5:
        {
          address = " ";
        }
        break;
      case 6:
        {
          image =
              '/9j/4AAQSkZJRgABAQEAYABgAAD/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAADFgAAAzMAAAKkWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPY3VydgAAAAAAAAAaAAAAywHJA2MFkghrC/YQPxVRGzQh8SmQMhg7kkYFUXdd7WtwegWJsZp8rGm/fdPD6TD////bAEMABQMEBAQDBQQEBAUFBQYHDAgHBwcHDwsLCQwRDxISEQ8RERMWHBcTFBoVEREYIRgaHR0fHx8TFyIkIh4kHB4fHv/bAEMBBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/CABEIBQoFCgMBIgACEQEDEQH/xAAaAAEAAgMBAAAAAAAAAAAAAAAABAUCAwYB/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAIDAQT/2gAMAwEAAhADEAAAAe9HpyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGzjW35cRkrHqOOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2TxFWkiKo999nPaXdaOIW7e5WORwMD2mwi6QGsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+bKr3XUjO6mVMSxyOUAAAABjSS6nSQ1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS5RNltNi6qdIR0OdAAAAAAAA57RLib5BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9sZV0612Z3HkEUAAAAAAAAAABGoeniVNEzw2gOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL4iT7GRlencRQAAAAAAAAAAAAAEel6LCp5pNhbQHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZKt86hzzOg50AAAAAAAAAAAAAAABW2Q5df0m+esVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb+NVvI342E0AAAAAAAAAAAAAAAAAAA17BQRenqNIgDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPlhc+5Y6BzoAAAAAAAAAAAAAAAAAAAAAcVdX1FfpNONoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEvjZcPcNA50AAAAAAAAAAAAAAAAAAAAAAACvp+oq7mrGsB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADmzoY8vDQJoAAAAAAAAAAAAAAAAAAAAAAAAB56KKJ0fPbRiLkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNhdDHd4x0AAAAAAAAAAAAAAAAAAAAAAAAAAAVlnj3nMtmv0ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLyFNw0CegAAAAAAAAAAAAAAAAAAAAAAAAAAAVdX0fOawGkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMsZkrrIw1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAUF/V1NWN4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW1TfZ9lDLQAAAAAAAAAAAAAAAAAAAAAAAAAAAABFlYHND05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOk53psbCKAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjm9cuJ6MgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABv6Ggv8ACwmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKaBZ1m+YVwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZeUt1jYRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZVW1TtmF8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAn3NNc4WE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAABX09vUbZhfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ9zS3WNhFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV9Pb1G2YXwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZeUV5jfoigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK2ptKvbML4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJv8AnuhwsJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqrLCv2zC+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbOk5rpcaCLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApYMyHtkFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHUcv0mNbBFgAAAAAAAAAAAAAAAAAAAAAAAAAAAABxQRt+j0ZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0XO3+VSRnYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHN68sfRkHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9orrOpwysAAAAAAAAAAAAAAAAAAAAAAAAAAAAB57rObHoyDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcU9rHbMY6AAAAAAAAAAAAAAAAAAAAAAAAAAAAANO6MUA9OQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzrLCO3Ax0AAAAAAAAAAAAAAAAAAAAAAAAAAAAARJcHvKUejMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB75fR2vlz2VhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAACNJFNE6TXc822a9YDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADf0NDfYWE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT19pV7ZhfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN/Q8z02NBFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU9fLib5BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0XO3eVTRnYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwOe1noyDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaVc2e3bz3DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEl13eVA9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfo9nvTjDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT3FFUxBvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSbIkvz6hwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5zoeZuQ2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2sqa5w0CegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR+fuabXML4HQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG3o+X6DG5AigAAAAAAAAAAAAAAAAAAAAAAAAAAAABiVEDZr3yCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRHcXc3l+jxvaJoAAAAAAAAAAAAAAAAAAAAAAAAAAACLX6NGkBrIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7pLPPtqMtAAAAAAAAAAAAAAAAAAAAAAAAAAAGGcMox6cgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmN7Pem9wzw0AAAAAAAAAAAAAAAAAAAAAAAAAAAVVrQ1MUbwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABey6q18+gc6AAAAAAAAAAAAAAAAAAAAAAAAABjzV5RaQGsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASb/l+kxvYIoAAAAAAAAAAAAAAAAAAAAAAAAACqrJEffIKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALmmmR28GOgAAAAAAAAAAAAAAAAAAAAAAAADVtru8qB6MwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHvg6TZXWPn0DnQAAAAAAAAAAAAAAAAAAAAAAAHP3PPXIbcBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/oeXvMbmCKAAAAAAAAAAAAAAAAAAAAAAAGsrK7LHfIKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN+hx0/tbZYaBzoAAAAAAAAAAAAAAAAAAAAAConUFyG0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe3/P7470LHLHQAAAAAAAAAAAAAAAAAAAABjlTd5G0m+YdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxeTK2yw0DnQAAAAAAAAAAAAAAAAAAAMeZ6Dn7gNpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtLSrtPPoHOgAAAAAAAAAAAAAAAAAAARaG+odIDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALexgzvPoHOgAAAAAAAAAAAAAAAAAAAaOe6Tm9IDWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL6Vp3efUOAAAAAAAAAAAAAAAAAAAAPOY6jm7nWNoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGzjo/Tz6gAAAAAAAAAAAAAAAAAAAAOf6CkuYQ2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIjzYXXpjqAAAAAAAAAAAAAAAAAAAAAqbau7yoHozAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWdZcR2wGOgAAAAAAAAAAAAAAAAAAAACJL095zo9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9qrvGtoiwAAAAAAAAAAAAAAAAAAAAHno5dNib54iuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW09n59Q4AAAAAAAAAAAAAAAAAAAAAAAY5CJSdNQXMYbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA26pkrv0w1AAAAAAAAAAAAAAAAAAAAAAAAAU1zWVyqG+YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzrLvPs0ZaAAAAAAAAAAAAAAAAAAAAAAAAAIkvA5oenIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0lH0GNhFAAAAAAAAAAAAAAAAAAAAAAAAAPPRz2ixrt8goAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrS00b/PQc6AAAAAAAAAAAAAAAAAAAAAAAAABEoun5zSdY14CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEtbZ93jLQAAAAAAAAAAAAAAAAAAAAAAAAAABVWuHec0nwds/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCdZR2rs5KL89J6AAAAAAAAAAAAAAAAAAAAAAAAAAAAA1bRUV/T6rnnFnXaRiKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLjH2ysY7V2O9nYc6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwzFXX9JjU8yt67WNIoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJXEXbbTM7r5+SOhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0Qq2/Vzl1/XXMEXIdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGywlWTrXZncaSRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGmBau85vX00K5pkiPpIdAAAAAAAAAAAAAAAAAAAAAAAAAAAADPjBY2EdqbCaivPSaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARpIpoPT67nm1rA0jSKAAAAAAAAAAAAAAAAAAAAAAAAGU+VdJt5GdwJuSehzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0RK+7d5y7o4FzVturSQ6AAAAAAAAAAAAAAAAAAGXGKwsI7UWE9FY5E0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5EmOqSH0+qp5xaQNI1CgAAAAAAAAAAAAAB7OlAkW8mLr52SOhzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0Q6+8Vzl3RQLmsbNdyHQAAAAAAAABtspVk+yzyvXsJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADGFPd5z8fp4dTSJMbWQ6AAAAAMrKVfaTssrxyJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEluqCN1EG4pWzXpIdAD3jyXMsc607jOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMau2d5y6+pdo1iubLzLdhoE9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa9goIvTw9ZnDKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//EACoQAAEDAwMDBAIDAQAAAAAAAAIBAwQAUGAREjMhMnATIjFAIzAQIKAU/9oACAEBAAEFAv8AGXsOvRcr0Ha9B2vQd08Lo04tJGcpIqUkdukbbSk/ovSn393hNEVaFhxaGLSMNpQoifpJURHnlPwiLbhUMVaFhtKRNP2LUh3evg4GnCoIqUDYD9CY5ongwAI6CLQNAH05C6veCm2DKm47Y/Wljo74HRFWm4xLTbYB9h5tHAJNF8CIiqrcZaABH7b7SOIQqJeAU601GVaABD7zraOI62Ta5+0wZ022IWEkRUfYUc9AFNWWBGyvx0Kl6LnLLClQigpZnmhcpwCAs2FFJWWEC1GKGLzKt5q02ritNi2lrXrT7GmZsMqdCiClukMa5jHY1uUhndl8ZnddJLO7LY7W9brKaytoFMxRBG7SW9hZTGb2Bd3B3iSbSyeI3uO8zA6ZOyOxu8qmqODsPJYY7nL3NDpksQdrd7dTcGSAm4kvskdruRxE1dvs5OmRwU9l9kJqzkcZNGb6SapkYdBvz3R3IQ6nf5fNkLHV6/zeTIYvPf5+RQ+a/wA74yGFy3+b2ZDB5b/N48hg8t/ncWQweW/zePIYXLf53HkMPmv87tyGJz3+dkUbnv8APyKPzX+d35Czy3+by5CHff5nN4hlc+RB235/myJnivzvLkUfhvxd2RRODxDD4r6fZkcHjvr3FkcH4vsnhyOBfpXBkcHvvszhyFEVaGMa0wz6ZX19v1BWKVGBBkEdtAHATFCFwdh47HTV7A5ye7HYvPgc/Ho/R7A5y+7HQ6Fgczq9jzS6t4E6urmPQ11ZwE10HH4OBSeDH4a/lwGcvsx+Ouj2Azl92PiuhYDLX8+QN9mAPdXcgi8N/X4X5yCCvtv8hdGshhL77/NX8WQsltdv81ffkTB7276q6I4W48iYcVsvXbvhvACvv7kyUF3Den11dyaGurN5NdByeCt6lLozk8VdHrzNXKBXQkvMpdXsojLqzd1+CXUsogleJK6M5TGXR27zlypOiguo3aQW53KoZatXVwtoZXDLR26zS9uVouiguo3SSW53LIRahc3i2N5bHLY5c5pe7Lox727iZbRJVIsujnsO4zD65hEc1S3vuemHzmI6orDiOBbSXRHj9Q8yYP0zS2zHNSzSIurVrLoi6quaQe21vr+HNYFslcGawfi1yeDNYPZa3+HNYfFa3OzNY3DbF+c0Z47Y7y5oltk8+Zt8ltmcuZxue2zvnM4fLbZqezM4FulcOZwuy2vdWszi8NtXMutCy4VNptC3OsHuVFTL2WA2CiJclomGyok0LLB+LpJTR7K2ert1m8mVw01eus5PblcFLtKTVnK4afhupJqOVgmg3aQmj2Ux01du81OuUwhvEkdzWUsjtbvDo7HMnihudvMwOmTNsGVNNo2N5JEVHIypS6pkbccyptoAvxgJ05GWlRUx5NabjktNtgGBEIlTkaiRRxpEVVbjKtNtiGDEKEhxqMCHFgEipuNQAIphKpqjkYVo2zDEgbM6bjIlIiJh7kcCpxgww5tgypuOA4o40B0cYkpU0whEVabjEtNtAGMGAnTkajEhwQGzOm4qUIiKY2qa05GBacZcHAG2HCpuOA5EbIHRxiSlRUvQiRU3GWgbAMmIRKjjJRtmF2Blw6bjAlIiImVGwB0cc0pdUuAipUEVaBsAzAgEqOKlG2YWwGXCoIwJSIiJmhsAVHHNKX5soipUEam2wDOiESo4tG2YWJtlwqCMCUiImfmwBU5HNK6p9xEVabjEtNtAHgQwE6ci0YEP2AAjpuLQCIp4HXqjkYVpxkw+o22Z03GFKTp4NcYAqcZcD6DYEdNxhSk8IuMgdOsmH7BRVVqNSIieFXWBKjbIP0tMEdNgIJ4XVEVHY39kRVViOg+HHmRcpwCBf4bBTJlsW08OmKGL7Kt/w2CAPh9eqf8AM3/pV//EACMRAAEEAgIDAQEBAQAAAAAAAAEAAjFQEUBRYBIhQSAwgBD/2gAIAQMBAT8B/wARYKwelAH4vEoN5WB+Cc9HAJQbysD9uPzooyUG8rH8jPQwCUG4lYx/QhHoAyUG86BblEYm+AygMaZbi7HtAY1i3FyPaAwNgj7bj36QGBtEfbWSmjA3HD7aNG6R6RsxG86yE75iybPUW0BmxEUBmxEUDpsRFA6bERQOmxEUDpsRFAZsW0BmxbQGbFtAbFs9RbPURO+YsQMoNxQeKIxXiKIzXtojNe2eoiaExYChMWIoDFi2KB02LaAzYj0gcneLs2bZ6iN0xaFCNx1q3cM2rTtk+kbXKEbTj8t2n5tE5NuJQOdhx+XLTjXJwjclCNZ12I1nXRQjWd1Ex1ExdCdcxdNnXMXTdg9SMWwnbMWzZ6i3cM2oGBuOH20a33ndPsLGLENygAKAtCIImslBqAxSFuV4kTUDJQbygMVBGUQaQAlBvKxisIBRbwsY3sINQAsSvFeO0ASg3lAYtiAUW8auEGoAXcrxXjoDJQbygMdAIBRbiP6AEoDnopAKLeFjH7Ayg0DpMot+/iSg3700jKLcf8DcdQ8f9Lf/xAAmEQACAQQCAgEFAQEAAAAAAAABAjEAEUBQIUEyYAMQEiAwUYBx/9oACAECAQE/Af8AENx3X3CvuB9KLATRcUXPVfcaJJn6qvZ9HZgKL/yixM/mi359FJAmi/8AKLEz+pY9DLATRcmKJ/YrW4rjr0AkCaZyeBV/3qxFAgi43zPaixPJwgxB4pWBmd2SAOaZieBjK3R3LGwpmuchW627Gwom5vlK1uKG1Zrm2YrX42jNYWzQbHaMbnOQ3FtkxsM9TY7Jzxng87J880sbF50CeOxedAnjsWnQJ47F50CeOxedAnjsXnQL47F50CxsfkzzSxsfk0AjYvGeJoRsXjPE7Joz1nYs1uaLE597UrkTQt1r3nRL46950Sxr/kjRCNe/joVnYNGhWdgKM6BJ2F+qYWOgQcXq+wcd6BRYbEi45plA5Gcqidm44zQOdowuM1RztWFjbMQd7VxzfMUWG1YXGWBc7aRRFjbKQc327jvKUWFtuRcURY2yEW5vuWW4x1W5oCw3N+qYWOMm7acb443bTjfHuhRnGSd0Yx0ndNGOvlum8ccTunbi2QpuNv1RNzlIebbZoy1nbOeMsHnbOesxTcbVjc3zEPW0ZgBYZoNjegQY2BouBRYnQK5E0rAxrDxNFwIosTOkVyJpWB1BIE0X/lFiTc6hWIpWBmv+aMsBNFyYonWBiIoP/aBBjOPE0XAiixOxvaKDnugwOUWAmj8nQokmdsGIoODNA3jEPE0XAiixO7BIig57pWBwCwE0fk6FEkz6AGIpXBmr3j9bMBTOT6KCRFK/RoEGPzZgJosT6SCRFK/Rq94+sTTN0Kvf0wMQeKVgZn6MxPqCt/pb/8QALRAAAQMDAwMEAgEFAQAAAAAAAQARYAIhUCJwcRIxYTJAUYFBkTADECCgoVL/2gAIAQEABj8C/wBMu1FX6XoK9C9P/V6dmPQV+Ar1ldivQFb/AAdNTanZNgHXZler/i7OrBv4XNkwtTsjakrVV+l2dMB/Kw9I2P8AStVStSPYdA2N0glayrD2dWxfbpV9XtudiGF1rLKw9wyY7CsAStZZNSPd/BTG2wb12TUj3zFXvsBewVhgWN09NxPWpDpzc4V6LFMQ06eqwTC2H8piJuwTm5xTFfImtrJhjGT0dviZubUphbH9VH6mPVXkuqm1S7NLuurtlOqn1S1z6ct10/crYJhl3HpMqv3zHSmMo6vwM11iTsgM1dGmTP8A+c4Kx9ybnOEJpIB5zx8yR/jPU1SSo56qSU55pIB4z9UiAgBkVMAHEipgFO0VMi+oAOZEeIAOZEeIAOZEeIAOZF9QAc7RUyIQCmRUwCmRUwCniRU8wD6kQPneKqRjP1SOnjP1cyOnaIbwVSQ856viSVZ6qSVZ6qSVbQMFeyfqfPM7KxBWoNIPMCYo0x6mCUmPUwSiPUwSkR4HaOkwOqP8QImQVCBVSBoEB5kFMCpEgB2jBgNRkI2iIgFRkREAb5kVJgAHxIwc+apH4XfONUWXTR2kwPzm6uZPwc0TKKqf1mjKBmqaZQ6fMnxKRmXlNVOYMqGYFMqdA5cytvjLEyxvnLCmWOgcqZb0/GUJlwOUFHxL+Mkainl/jJdAmPQfrIP+fxMnCf8AeOcp9oegTUeLYx081q5xlXE2qxlU2qxlU2POMq4m33jKuJtTtFTxjaudoqppTzjvqaU46maP4xwPmaVY4zQnzjquJoNoOzrsyAx5IurgiXgm5KsMn2ZEeZa2VqllIywPjaKk+ZZUcsZZzliJYB9ZeqVU5gVSo1ZgyoDMkSh/wM11j7k7nSmGaYrRdXBEjvpVhntQdaC6YgiP6rKwgVw60FMQY1YOtZZaRBrh09BTVBotpDrWtIaFXT02VxErBai6taH/AAV2eHOzcq+qKXC06kzNCLAlaiysIxqDrQVqBEE0hay6sGjl1p0rs8A+FfVIrhabpiGzTUgrWWVhJrhaSrjLdmWrUrSvsytdXcZCwdayysJhqDrQVcYzsy1alaa9mVrr8jDMA61FlYTrUAVoqZXpwXZuVq1K0/7Mrak3vGAJWqysNhNQdaCrhvcaQStZWkNsRdabK4f2mkLVdW2N7MV2cew0hPVfZJ+xXyP5GCevZa1itQ/hc2C0jZi4T/0/1/kwCeu52c+CmP8AdgF52eYpxen+zDaC6/P+yr//xAAuEAEAAQIEBQQCAgMBAQEAAAABEQAhMUFRYFBhcYGRobHB8HDREEAw4fEgoID/2gAIAQEAAT8h/wDjKBW0vShMRzJULh3rV9yfuvtH7p5Dnc+GmRRMLY/hYFYBXQJrD4OYB607FLqr+qzw6EetHxR5rWGd8KAEAOhH/hgUgF1pr9zHN/CbEhaAvtUOoGqk0Ov0Fa9c1aHgByP8LJAF1aZwBsZvNo/B/T2q+xnNYKywagrPyjFZohADp/kgEtgxpbwJYzXV/B33Cr6IHNsUCFnULFR8RM0l80f50lMcemn4M6U9nl2IPNM3h5BPrRRCOrj5o/otIh1g7W/BRdguuBrUMsDm4+KuAlq0AEAHb+J/pNI7FhJ1z/BDICnAiaiGBoYtCWx1cf6/WmCslx0aRwSGE/ApJQ5GNOh6QuvVoGAFRR/ZlWCWfimQqNc+Z+AgoAVWwZ1cBGmb+qIgGvP+9FXomJUAEHBMHf5UQjnOL0o/OiFzeAogA4jUrLm6m/McKmg1OXeoXq7gdOCNSF4xMn/dFkCLI76hJVvGbRIQHBwb2GCY1YS0TBN7xlVyqE+FKOExzkaYUlcHTk145b0x4BiuVQB6ubwwAUCJcpmzOfMdOVTbePXCsYfUaAAAwOHnIYcXI8+tXGEhLI4m75zyzpmFBiDjREQWMuINHhfcpEUZCyOJu3vFTIUGA58UgpADDWmZhIi0OJuvG1NgwfPKi1gjittK+TXnuslazXQowUAWKz4o04a1qwScnTdONi62jWrli3f4OLCqzp0KEYee6LgNHm0cZljXLPTWvbcxKgxWDrQ6SX651nxhokLhL06GTZ5Zfee5WhsrXTq8bcKkClLU0PG5YVS93bLjnNcpEZFxR657kUXFhRAgMOONWmWUnfH1ncfSr6wHrx7ohTzf43H161CnFQ8f949bmIT4r5vuONak8ekdQlJd5P323GOXA9OPNGHzU3EeZIebbAF7UHcRg85/jPjxvfV3cRnkS+jRWfHhd8n43Fgch2Bi+buLH6vc2AfTem4vVfc2B9/k7ha9R9zYH0uTuL1X3Ngff5O4sfq9zYH2uTuLA5jRx/Bar7bi9A+1GPH7Tv8AjcXv/Z/jPjuVK55PxuL1/wDGfHsBze+4rH5PejDj7kmg93cSjRCjDj+JyA3Ea6UYcf8AEj2Nx3PyPbjzV6843HieX2OPOFY3V++4uWtOX5cfdzqr6u415X3ePNijAddxfqr+laz47amg+1fvcXOlb0+Bx5x1vtuTD6J7ce9N802tpuNYeQ+/Hre17lOPTceA5Dx5wuaVr13CyArlBNFCg6N2lV3CMI0/XHoE4kzHJop2SImkIROFrbfJUCZbEVdcTuuwmQiNOhNm3M28BXWfF/iis9g5UQTFE8f929772f4z2DlXyfG3lL5x5t80YbDk0Avn/m3ly5Hw0YbCcKUhoB8/O3+dAbDm2qxt7lUAak+dhcixacZ291wzpW5w7Ccajb1rN9dvdaiSwRPbYUBsWXo0ept+R6sebfNGwZNML5/5uDkQj4Zo2DMjQD5+dwc9L055Y2C+rJuFzy5PXYFqeVOU6s7gSptMz5/5sDoZHm1R9+9NwdKhyiT32BDBmB6V+2NwzJgMPe2wJy5L99xXyq4ksX68eBFYDGmazbHLL7y3GqYl4hj1KLYNViIZOv8AGfGWmrFE3GKmppYrN+nLcv0rlOHjTU36Dtbc8Aah8/PGuRAtOK6/fnc99OT0fXjVu52K+Hc/LiI/e3GWowNVfvfdCEMkTszSEBmTxhqMGAA7f7d0fNqnulv1xhglwKRliqvf67pxDWT5+OMWy3SCuhzOn03Tf+DZ+9Qo4vdPq+x87qSAxETtQkYIPFnCpmYDB23V0q8sVB0y4q1ypKlbriq9c913I2Md+LRkYmV6G7GEYjJ2oTcEHijU+GxY7Y7s64Z1KLFSdHigq2Yg61K3cc92ypg2ej9KOJNSgwuerhu+0Lez9cSC2AJacJus7u7TUOuKzyKEbmHEZQ2F150bv6kmZV87mLUrnw8swrDVpVKsqyurvFCREZEqALJYaPDgdIDGlkyBYOW81FmRsnKkIJceGNIDQF150b0u7H2MPSOGIdYBNNCbqr3+u9Vb6vPDIqWEGhHjehXw/PDPa+5WvXep8p7cME9HeuPhrF6/DhhkOap++N6mOpfHDBJaqow3qY73u8McIqxGjvUQfL7cNMDovd3pyqwjlw0x1B9DehkNQetHDGsJ1HzvQyHNfBw7Eck8b0N+hPtw77Zk0XN5YeaF3yD34ce3D61+t5OD0odd8Dhwh6quX3DeYjnr7vDhaNaSLaW3iCYEtAmr9MarEdqVfEAeHwYBMkNyn4Q5kbu9omoroBZwvQsAHIjiQEhBOZVySnS1Z0Qhem7DGNbeasGgjijaolqz5N2HmyPhn44sYFgw8L+92QDoL8fPFpNIjz/zdfSr+XYOnFrfyuV0w3XAHUvx8cW50FOKaffjdQTYxWKIjIPDizhUNyWTvfdUOcBl7Xo4s1GbMh7f93Tk1jedj59jjFhZX+9q1jt03RGWtq1Pi/XOsuLtyGrB4NumXpuiCRmrq5UcYamBXLfBqNynftUeEOeLV6LN1407CRIavTIYDjRREDEctxAzAKuAEzV8tc7rV1CTNxox444URAfCjSwNMHzTrCMk28EgCrgBNX9RxjNoa11cfP8AE7ANguynxmNF+aehHmbaJDLQqOYGhjQUQauexooQ0aPFHJfmm5GhiztXHTvSoItTKs99j91AgGyggAlTaz0yrHxNcvNHa+0XLyaxAd6uTLG1ijYANnJrU2h0i3irkQGYT6bNKg1A52L2q9iWqUAEAHbad+AdSzV7QPFIlJGSQnbZDIIaBNICR0CX/VYMLq3dsAQGi1ys/tP7pWOaRZ2Ixfb3Ug81iHWMFio0Q6VFG2gEARq4pWhh4qVWAzL+nHy7ASuBUIpFzbPirkJap8UAWA8bhwpHUxq9OPhP3TKhHKHjTogmeVKhDkL+tGWx1zo3I0RBJ0pV2HRwq/LGph54r57VGJBq29KgVK52PFRAAcjdTcvV6ualX9x5WaCIE0SHxxBsGXKmXxGBj5qOi6uNG7nCiYDRJSLocmsawM5k80cKMc+1RqQatvSolSudjxUSIHI3o6Na2OZan5YfD4opBE0SHxwXHTvTwpGlO3iTgX9awanVxo3x1o2AMpKJulmD+6vyAZzJ5o7X4B9wq4yGtlRClaNjxRMEDkb+cKn265lqusR0h8UiKETJLn9xkQaBNQCw6BL/AKq7Aurdo/AeHPurM7T+6RhskxZ/r/cKYi4XcAosZnGC3moUA/BBIAI4zVzc9MvFSSgMzDxX3D+l0pCJDNbBUSuemVEEAAwAt+DGrmc0VfIDmfqvuH+bp7UrCJmpYqJWfpQCwEH4QavokzKxA54V7ZW/xigXtNAXRcYMPNEQAGR+FGj1JyizWVhk5Pf/AAdaIJfXagAGur+GIkCZzTEpPN8UyKJCNxxP/JJCuAZ1gFihkUfhsGXkJUbY0TB/ktC1dDnUICUXdfw8sMRpC4jZ05NW0osfVzfxABACOJXOpn/+Q5/+RH//2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBxSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACT5nLPOEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSnHPPPPPIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSkHPPPPPPPKKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACctPPPPPPPPPPLOgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACevPPPPPPPPPPPPPPLCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJ5PPPPPPPPPPPPPPPPPGJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATnPPPPPPPPPPPPPPPPPPPPNyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXPPPPPPPPPPPPPPPPPPPPPPPJiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcPPPPPPPPPPPPPPPPPPPPPPPPPLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbFPPPPPPPPPPPPPPPPPPPPPPPPPDIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1PPPPPPPPPPPPPPPPPPPPPPPPPPPAIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPPPPPPPPPPPPPPPPPPPPPPPPPPPPLHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9PPPPPPPPPPPPPPPPPPPPPPPPPPPPPOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIfPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLJgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF/PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJvPPPPPPPPPPPPPPPPPPPPPPPPPPPPPLIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbHPPPPPPPPPPPPPPPPPPPPPPPPPPPKMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/PPPPPPPPPPPPPPPPPPPPPPPPPPPLKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFfPPPPPPPPPPPPPPPPPPPPPPPPPPPEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfPPPPPPPPPPPPPPPPPPPPPPPPPPPOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALvPPPPPPPPPPPPPPPPPPPPPPPPPOAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPPPPPEIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEfPPPPPPPPPPPPPPPPPPPPPPPPPEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvPPPPPPPPPPPPPPPPPPPPPPPLAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUPPPPPPPPPPPPPPPPPPPPPPPLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM/PPPPPPPPPPPPPPPPPPPPPJAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVPPPPPPPPPPPPPPPPPPPPPEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHPPPPPPPPPPPPPPPPPPPPPCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVPPPPPPPPPPPPPPPPPPPPPAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAPPPPPPPPPPPPPPPPPPPPPPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPPPPPPPPPPPPPPPPPPPPPNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9PPPPPPPPPPPPPPPPPPPPPCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/PPPPPPPPPPPPPPPPPPPPPKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL/ADzzzzzzzzzzzzzzzzzzzzyykAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCzzzzzzzzzzzzzzzzzzzzzzzzzwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHzzzzzzzzzzzzzzzzzzzzzzzzzywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfzzzzzzzzzzzzzzzzzzzzzzzzzyggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALzzzzzzzzzzzzzzzzzzzzzzzzzzgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDzzzzzzzzzzzzzzzzzzzzzzzzzzwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtzzzzzzzzzzzzzzzzzzzzzzzzzzzxg0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQfDzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwjYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyy4kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlIjzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzAsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2rTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyAskAAAAAAAAAAAAAAAAAAAAAAAAAAAAAksRzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxRYEgAAAAAAAAAAAAAAAAAAAAAAAAVqTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwC8gAAAAAAAAAAAAAAAAAAAF+RzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxRY0AAAAAAAAAAAAAAAnqTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzCsAAAAAAAAAAA17zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzww8kAAAAAAXbzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxQMgAAVvzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwiUCTzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyBzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzjzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/8QAFBEBAAAAAAAAAAAAAAAAAAAAwP/aAAgBAwEBPxBNCAAAAAAAAAAAAAAAAAAAAgREREAQAAEABIAABAAAAAAAABQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/xAAWEQADAAAAAAAAAAAAAAAAAAAhgMD/2gAIAQIBAT8QoCwoCTAiIEAQICCACAACAAAAQQAQAhCIAEAiCI7u6qiQRAAIFTAGICEgACUBQSIgAEQAAhAABoiOogAQcEgEAAAQEACAIICAIgBABACECEBAAgAhAIQEACACAQAEAgEAAACy3//EAC4QAAECBAQFAwUAAwAAAAAAAAEAESFBUGAxUWFwEHGBkfBAodEwgLHh8SCgwf/aAAgBAQABPxD/AEzQAJE4HU2tWFJ+otmgQCgAaAF4APhGGJe6UpcnE/wEWkAkjRWC4bKHRAcUhgpPf4o0Yox9HIrmGydQJArECeGEsE0eEIPqE6MQWyMAAADDAhI/rPQqwgCURGex4LgAiwwGNb0YSCNisBwABQyeKdyTCBkPSia1nYgwK4HARaO4sBdfTy4BBMJ/NhoNIFA0erwHaJJivEy2Ed4AtCAxmOWKDFzkieb1uCxbtgkFSwFPGo6NCHuQ0Jlfoal4IwZ1FEgGikovvvGDJEk1yGz7WR2JBx5wBQp43hjShJ+OlIqZvYBZZ1KymDZIBJ3p5BQOj4TALlTgoLLFoGu8AAQIcxYsQBAAgyogpYErvrQgDAiWCHwKnjBASxdgADTSSgZAKrhOxXZj0RBVNVgB/B9ow0AAGKH6GCGh2jdxA5k3SK3OATEEwblaBgFAGdzp0ARVygPeIAJXMMyj1wdnKHO5lBAFkCoQWG0LxoGeCKfFd50G4xhXwE0aUi+64z+oRz9ivD/bQmLjgP8AWztGMwjpOvM3GuUpV0eDea2ggABuQyF9ZL4rxQ9JXED7xcQDHtm0Qse07RDj2y4gm2i4UNtJV8cF1hXEPqisAEx1O4htXjDcgSJlZV0eB3FAVfLErlCQQidcPAnuKQmsACe4xC1YiTrwrj6J80snXDwCe40x4YxU64eDlxJDFOaFeY3CorjAfRVeHqi2iAEeS3/LiwRV6sTF8wXIESvSFzDbkAVeE5SVxBK/wcIIMEpCWFGvBIK5x4OuosXACMACAABmEGwlmzCltCXgBWA7RBJgAO0bnIErhAQR0J2AbhHNOaK52EcLfRRnQPjL8rCB+s0XAB0yLC06MuEFBjDtYB+6V0QFEBKAeh1xghq9YEbhQmNg9AtII3CeHLBbwHxL9lxi9gr7FcdgCRD4r+vZuMMoyVOuFNBg5ZC5UrBiXA+EiJDGsjwACmIUgmUuX4flP7qo2hCi/qDW3kDwnueDFapGdjVM10A0k+lZZwroJiDLQjMBh12iDEgZuC/p8GrGC0OdogboEAzYHdX6faEBzgN2pQUEAsydUN2jhRHpIJ1U47Sud2EANEiIKrE8H9h4B5QSYGPA56qYDDMdQ+xEAGEFAxrg3LaNTEB5B9owYgPUCsPLaCgC3kxRHedEeSMSxgAqdIjPZuSLOkTvMG6NCosHBzprqAmr1ObT8M1MYogLaJLZGYMzk7/YwAMgNUzHkE72AU0poivRinU5qmNCF7KC9XT1MAOgNoYPEcL1aQzoDeWmDtGwTrAWzmvUwAH5phgEHP3ojqCPimFPZRiCvMOXUk6a+bNegA3nFE6b5ymvQ5/NOHDvQIWgDIUaCNOYKd/Z/gS8CMYEP9q+wtCPVJaKAcWtEP8AndqbQDoAafeyqEy7hAMIA0qhu58QCaDddEQE2cDbrj+Vc/TUeCBrrgAP4vYU6oUDxXaa4cKE9oGggbrAYb8Rh+cxukIkASM7yZ1gCCUJ3aLAjgIxHZLoAQuYkw4nWxMw7CFxmaxMQgABhXwOBbWq8DmWk05uhQJ3LfJYAAiHWixVucjCvDxY/NcCCt2mP6GsQkowlISJdbG0HiI+2CQVgA9wMDWv/lORuBZRsaMQQ/BAg7yzjaQAOWXoA8SCIAOXAFnOBmEaoI5U+EANjCzihsPGCpJhAyFpgKZjliRi7WU0gANcpiwGoIgM2vhWqWLGCcfgQAkiCAMqGcgcW4D/ABpAhd1QLDgNYABQyFSkBAZC4TwSHTSCnKJQSK5GuBhoMJnOGEe7iFxua+kHnmV9yIQbPesAg+ATBgUSYuoEH4uj/ZQ0eYapLUINeGNj1aBsWGt3XgPYZAn7qX90Q0wU4AKPjEwZFUmL0iQ4HxFBclJ0gO4QDjQzpjJLmt3XylwFYDnzE0IZMNCAGQOE5yQGTdJi/gBYcNUxnlZl2FfrgWRIKYR3FRUBJmZ+wgANlhk9SHGYDHgKwABlQnI3A2ILsKRHzuNwhMs19KDagyWHCFgAbGBBPrzls/ROvoRMGsIcjDQCAEAAS2ROncLUV+omBO6ZBDeokBY6wNlRczmgMNkDH6Ia2a/EmfGZu5swWnHACgKMVA/yQIBrEDL9oUAiinckzEPSYBsUAAgYuoa7QQcgEwKJCTi7Qim/1s3/2Q==';
        }
        break;
    }
    notifyListeners();
  }

  checkCard() async {
    var dataCard = [];
    for (var i in itemEdit) {
      if (i["ID"] == getItem["ID"]) {
        i = getItem;
        getItem['name'] = name;
        getItem['family_name'] = familyName;
        getItem['mobile'] = mobile;
        getItem['id_no'] = iDNo;
        getItem['address'] = address;
        getItem['birth_date'] = birthDate.substring(0, 10);
        getItem["image"] = image;
        if (name.isNotEmpty &
            familyName.isNotEmpty &
            iDNo.isNotEmpty &
            address.isNotEmpty &
            birthDate.isNotEmpty) {
          getItem["is_active"] = true;
        } else {
          getItem["is_active"] = false;
        }
      }
      dataCard.add(i);
    }
    String encodeData = jsonEncode(dataCard);
    final prefs = await SharedPreferences.getInstance();
    prefs.setString('cardInfo', encodeData.toString());
    notifyListeners();
  }
}
